services:
  frontend:
    image: frontend_stockhub:latest
    ports:
      - 5174:80
      - 5175:443
  backend:
    image: backend_stockhub:latest
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      CLIENT_ID: dc30ef57-cdc1-4a3e-aac5-9647506a72ef
      CLIENT_SECRET: AzJ8Q~4d_sM4ru2h.aE7-5GHCRjsTjvjiGmTSbNK
      DB_USER: stockhub_user
      DB_PASSWORD: stockhub_password
      DB_DATABASE: stockhub
    ports:
      - 3002:3000
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: stockhub_user
      MYSQL_PASSWORD: stockhub_password
      MYSQL_DATABASE: stockhub
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3320:3306