# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop

pool:
  vmImage: ubuntu-latest
variables:
  - group: "stockhub-front-variable-group"
  - name: sourceFolderFront
    value: "frontend"
  - name: sourceFolderBackend
    value: "backend"
  - name: deployDirectory
    value: "/home/stockhub-deploy/deploy_front"
  - name: deployDirectoryBack
    value: "/home/stockhub-deploy/deploy_back"
  - name: currentSshEndpoint
    value: "ssh-stockhub-deploy"

jobs:
  - job: buildfront
    displayName: "Continuous integration Front"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
        displayName: "Install Node.js"

      - script: |
          yarn install
        displayName: "Install dependencies"
        workingDirectory: $(sourceFolderFront)

      - script: |
          yarn run build
        displayName: "Build application"
        workingDirectory: $(sourceFolderFront)

      - script: |
          yarn run test:ci
        displayName: "Run tests"
        workingDirectory: $(sourceFolderFront)

      - task: PublishTestResults@2
        displayName: "Publish test results"
        condition: succeededOrFailed() # because otherwise we won't know what tests failed
        inputs:
          testResultsFiles: "$(sourceFolderFront)/src/reports/junit.xml"

      - task: PublishCodeCoverageResults@2
        displayName: "Publish code coverage"
        inputs:
          summaryFileLocation: "$(sourceFolderFront)/src/coverage/cobertura-coverage.xml"
          reportDirectory: "$(sourceFolderFront)/src/coverage"

  - job: buildback
    displayName: "Continuous integration Backend"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
        displayName: "Install Node.js"

      - script: |
          yarn install
        displayName: "Install dependencies"
        workingDirectory: $(sourceFolderBackend)

      - script: |
          yarn run build
        displayName: "Build application"
        workingDirectory: $(sourceFolderBackend)

      - script: |
          yarn run test:ci
        displayName: "Run tests"
        workingDirectory: $(sourceFolderBackend)

      - task: PublishTestResults@2
        displayName: "Publish test results"
        condition: succeededOrFailed() # because otherwise we won't know what tests failed
        inputs:
          testResultsFiles: "$(sourceFolderBackend)/src/reports/junit.xml"

      - task: PublishCodeCoverageResults@2
        displayName: "Publish code coverage"
        inputs:
          summaryFileLocation: "$(sourceFolderBackend)/src/coverage/cobertura-coverage.xml"
          reportDirectory: "$(sourceFolderBackend)/src/coverage"

  - job: continuousDeploymentFront
    displayName: "Continuous deployment front"
    dependsOn:
      - buildfront
    condition: succeeded()
    steps:
      
      - script: |
          echo "VITE_REDIRECT_URI=$(VITE_REDIRECT_URI)" >  $(sourceFolderFront)/.env
          echo "VITE_API_SERVER_URL=$(VITE_API_SERVER_URL)" >> $(sourceFolderFront)/.env
        displayName: "Generate .env file"

      - task: CopyFilesOverSSH@0
        displayName: "Copy dist to remote server"
        inputs:
          cleanTargetFolder: true
          sshEndpoint: $(currentSshEndpoint)
          contents: "$(sourceFolderFront)/**"
          targetFolder: $(deployDirectory)
          readyTimeout: "20000"
          delayBetweenUploads: "5"

      - task: SSH@0
        displayName: "create docker image"
        inputs:
          sshEndpoint: $(currentSshEndpoint)
          runOptions: "inline"
          inline: |
            sudo docker build --no-cache $(deployDirectory)/$(sourceFolderFront) -t "frontend_stockhub" 2>&1
  
  - job: continuousDeploymentBack
    displayName: "Continuous deployment back"
    dependsOn:
      - buildback
    condition: succeeded()
    steps:
  
      - task: CopyFilesOverSSH@0
        displayName: "Copy dist to remote server"
        inputs:
          cleanTargetFolder: true
          sshEndpoint: $(currentSshEndpoint)
          contents: "$(sourceFolderBackend)/**"
          targetFolder: $(deployDirectoryBack)
          readyTimeout: "20000"
          delayBetweenUploads: "5"

      - task: SSH@0
        displayName: "create docker image"
        inputs:
          sshEndpoint: $(currentSshEndpoint)
          runOptions: "inline"
          inline: |
            sudo docker build --no-cache $(deployDirectoryBack)/$(sourceFolderBackend) -t "backend_stockhub" 2>&1
