name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"


      # --- BACKEND STEPS ---

      - name: Install dependencies for BACKEND
        working-directory: ./backend
        run: npm ci

      - name: Build BACKEND
        working-directory: ./backend
        run: npm run build

      - name: Tests BACKEND
        working-directory: ./backend
        run: npm run test:ci

      - name: Tests with coverage for BACKEND
        working-directory: ./backend
        run: npm run test:coverage

      - name: Upload BACKEND coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: ./backend/coverage

      # --- FRONTEND STEPS ---

      - name: Install dependencies for FRONTEND
        working-directory: ./frontend
        run: npm ci

      - name: Build FRONTEND
        working-directory: ./frontend
        run: npm run build

      - name: Tests FRONTEND
        working-directory: ./frontend
        run: npm run test:ci

      - name: Tests with coverage for FRONTEND
        working-directory: ./frontend
        run: npm run test:coverage

      - name: Upload FRONTEND coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: ./frontend/coverage

      # --- OPTIONAL: UPLOAD TO CODECOV ---

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Add Codecov token to GitHub secrets
          files: ./backend/coverage/lcov.info,./frontend/coverage/lcov.info # Paths to coverage reports
          flags: backend,frontend
          name: code-coverage-report
            
      # --- DEBUGGING STEPS ---

      - name: Print Node version
        run: node -v

      - name: Print npm version
        run: npm -v

      - name: List installed dependencies for FRONTEND
        working-directory: ./frontend
        run: npm list

      - name: List installed dependencies for BACKEND
        working-directory: ./backend
        run: npm list