name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies for BACKEND
        working-directory: ./backend
        run: npm ci

      - name: Build BACKEND
        working-directory: ./backend
        run: npm run build

      - name: Tests BACKEND
        working-directory: ./backend
        run: npm run test:ci

      - name: Install dependencies for FRONTEND
        working-directory: ./frontend
        run: npm ci

      - name: Build FRONTEND
        working-directory: ./frontend
        run: npm run build

#      - name: Tests FRONTEND
#        working-directory: ./frontend
#        run: npm run test